name: Настройка кластера K8s

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
  - cron: "15 7 * * *"
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Проверка первых команд kubectl на  minikube
      run: |
        minikube start
        kubectl config current-context
        kubectl cluster-info
        kubectl get nodes
