name: Dockerfile CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
  - cron: "15 7 * * *"
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build helloworld Dockerfile
      run: docker build dockerfile/helloworld --file dockerfile/helloworld/Dockerfile --tag helloworld:$(date +%s)
    - name: Build helloworld-loop Dockerfile 
      run: docker build dockerfile/helloworld-loop --file dockerfile/helloworld-loop/Dockerfile --tag helloworld-loop:$(date +%s)
    - name: Build Go Hello Dockerfile 
      run: docker build dockerfile/go-hello --file dockerfile/go-hello/Dockerfile --tag go-hello
      
