name: Dockerfile CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
  - cron: "15 7 * * *"
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build helloworld Dockerfile
      run: docker build dockerfile/helloworld --file dockerfile/helloworld/Dockerfile --tag helloworld
    - name: Build helloworld-loop Dockerfile
      run: docker build dockerfile/helloworld-loop --file dockerfile/helloworld-loop/Dockerfile --tag helloworld-loop
    - name: Build Node.js Hello Dockerfile and test the image and running Node web server
      run: |
        docker build dockerfile/nodejs-hello --file dockerfile/nodejs-hello/Dockerfile --tag nodejs-hello
        docker run --name nodejs-hello-test -d -p 3000:3000 nodejs-hello
        sleep 2s
        curl localhost:3000
        docker stop nodejs-hello-test      
    - name: Build Go Hello Dockerfile and test the image and running Go web server
      run: |
        docker build dockerfile/go-hello --file dockerfile/go-hello/Dockerfile --tag go-hello
        docker run --name go-hello-test -d -p 8080:8080 go-hello
        curl localhost:8080
        docker stop go-hello-test     
      
