name: time-service CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
  - cron: "15 7 * * *"
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Сборка и тестирование микросервиса time-service (Docker image)
      run: |
        cd time-service
        docker build . -t time-service:0.1.0
        docker run --name time-service-test -d -p 8080:8080 time-service:0.1.0
        # проверка точек доступа
        curl localhost:8080/nanotime
        curl localhost:8080/time
        # остановка контейнера
        docker stop time-service-test
